bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('review/<slug:slug>/', views.review_rate, name='review_rate'),
    path('<add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product,
         name='delete_product'),
]

z_padel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)
    category_text = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ManyToManyField('Category', blank=True,
                                      related_name='categories')
    sku = models.CharField(max_length=5, null=False, unique=False)
    name = models.CharField(max_length=254)
    slug = models.SlugField(max_length=50, null=False, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    cloth_size = models.BooleanField(default=False, null=True, blank=True)
    shoe_size_man = models.BooleanField(default=False, null=True, blank=True)
    shoe_size_woman = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                default=True)
    comment = models.TextField(max_length=250)
    rate = models.IntegerField(default=0, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

products/forms.py
from django import forms
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .models import Product, Category, Review
from .forms import ProductForm


def all_products(request):
    """ A view to all products, including sorting and search queries """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "No search criteria entered!")
                return redirect(reverse('products'))

            querie = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(querie)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, slug):
    """ A view to show individual product details """

    product = get_object_or_404(Product, slug=slug)
    product_cate = product.category.all()
    product_review = Product.objects.get(slug=slug)
    review = Review.objects.filter(product=product_review)

    context = {
        'product': product,
        'categories': product_cate,
        'reviews': review,
    }

    return render(request, 'products/product_detail.html', context)


def review_rate(request, slug):
    """
    Function to be able to get the review information
    """
    if request.method == "GET":
        product_id = request.GET.get('product_id')
        product = Product.objects.get(id=product_id)
        comment = request.GET.get('comment')
        rate = request.GET.get('rate')
        user = request.user
        Review(user=user, product=product, comment=comment, rate=rate).save()
        return redirect(request.GET.get('url'))


@login_required
def add_product(request):
    """
    Will add a product to the database from the site
    """
    if not request.user.is_superuser:
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "The product was added to the database!")
            return redirect(reverse('add_product'))
    else:
        form = ProductForm()

    form = ProductForm()

    context = {
        'form': form
    }

    return render(request, 'products/add_product.html', context)


@login_required
def edit_product(request, product_id):
    """
    Will edit a product in the database
    """
    if not request.user.is_superuser:
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('edit_product', args=[product.id]))
    else:
        form = ProductForm(instance=product)

    context = {
        'form': form,
        'product': product,
    }

    return render(request, 'products/edit_product.html', context)


@login_required
def delete_product(request, product_id):
    """
    Will delete a product from the database
    """
    if not request.user.is_superuser:
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('home'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container add-product-container">
        <div class="row mt-5">
            <div class="col-12 text-center">
                <h3 class="mb-4">PRODUCT MANAGEMENT</h3>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>
        <!-- Add product form -->
        <div class="row">
            <div class="col-12 text-center">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-center">
                        <hr>
                        <a class="btn btn-outline-dark" href="{% url 'home' %}">Cancel</a>
                        <button class="btn btn-dark" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container add-product-container">
        <div class="row mt-5">
            <div class="col-12 text-center">
                <h3 class="mb-4">PRODUCT MANAGEMENT</h3>
                <h5 class="text-muted">Edit a Product</h5>
                <hr>
            </div>
        </div>
        <!-- Edit product form -->
        <div class="row">
            <div class="col-12 text-center">
                <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-center">
                        <hr>
                        <a class="btn btn-outline-dark" href="{% url 'home' %}">Cancel</a>
                        <button class="btn btn-dark" type="submit">Edit Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <!-- Breadcrumb --> 
                <div class="breadcrumb">
                    <ol class="breadcrumb mt-5">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i></a></li>
                    {% for category in categories %}
                        <li class="breadcrumb-item"><a href="{% url 'products' %}?category={{ category.name }}">{{ category.friendly_name }}</a></li>
                    {% endfor %}  
                    <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="row product-details-container">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <!-- Product image -->
                <div class="image-container">
                        <a href="{{ product.image.url }}" target="_blank">
                            <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mt-2">
                    <!-- Product name -->  
                    <h4 class="mb-0">{{ product.name }}<h4>
                    <!-- Product price -->  
                    <p class="lead mb-0 text-left font-weight-bold">€ {{ product.price }}</p>
                    <!-- Admin buttons-->
                    {% if request.user.is_superuser %}
                        <div class="admin-products">
                            <a class="btn btn-outline-primary p-1 mr-1" href="{% url 'edit_product' product.id %}">Edit</a>
                            <a class="btn btn-outline-danger p-1" href="{% url 'delete_product' product.id %}">Delete</a>
                        </div>
                    {% endif %}
                    <hr class="w-100 mb-1">
                </div>
                <!-- Product form -->   
                <form method="POST" action="{% url 'add_to_bag' product.id %}" class="product-form-add">
                    {% csrf_token %}
                    <!-- Size for cloth -->  
                    {% with product.cloth_size as size %}
                        {% if size %}
                            <h6>SIZE</h6>
                            <select class="form-input" name="cloth_size" id='id_cloth_size'>
                                <option value="xs">XS</option>
                                <option value="s">S</option>
                                <option value="m" selected>M</option>
                                <option value="l">L</option>
                                <option value="xl">XL</option>
                            </select>
                        {% endif %}
                    {% endwith %}
                    <!-- Size for man shoes -->  
                    {% with product.shoe_size_man as size %}
                        {% if size %}
                            <h6>SIZE</h6>
                            <select class="form-input" name="shoe_size_man" id='id_shoe_size_man'>
                                <option value="40">40</option>
                                <option value="41">41</option>
                                <option value="42" selected>42</option>
                                <option value="43">43</option>
                                <option value="44">44</option>
                            </select>
                        {% endif %}
                    {% endwith %}
                    <!-- Size for woman shoes -->  
                    {% with product.shoe_size_woman as size %}
                        {% if size %}
                            <h6>SIZE</h6>
                            <select class="form-input" name="shoe_size_woman" id='id_shoe_size_woman'>
                                <option value="36">36</option>
                                <option value="37">37</option>
                                <option value="38" selected>38</option>
                                <option value="39">39</option>
                                <option value="40">40</option>
                            </select>
                        {% endif %}
                    {% endwith %}         
                    <h6 class="quantity-topic">QUANTITY</h6>
                    <!-- Quantity input-->  
                    <input class="form-input" type="number" name="quantity" value="1" min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                        <div class="form-action">
                            <!-- Buy now button -->  
                            <input type="submit" class="btn btn-add-to-cart" value="BUY NOW">
                            
                        </div>
                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                </form>
                <!-- Safe payment container -->  
                <div class="safe-payment">
                    <h5 class="safe-payment-topic">Secure and reliable payment with</h5>
                    <p class="payment-method"><i class="fab fa-cc-visa"></i> <i class="fab fa-cc-mastercard"></i> <i class="fab fa-cc-stripe"> </i></p>
                </div>
                <!-- Product description text -->  
                <div class="product-description-container">
                    <p class="mt-3">{{ product.description }}</p>
                </div>
            </div>
        </div>
        <!-- Write a review -->  
        <div class="container review-container">
            <div class="row" id="review-box">
                <div class="col-md-12">
                    <form method="GET" action="{% url 'review_rate' product.id %}" class="review-form">
                        {% csrf_token %}
                        <h5 class="review-h5">Leave a review!</h5>
                        <input type="hidden" name="product_id" id="product_id" value="{{product.id}}">
                        <input type="hidden" name="url" value="{{ request.path }}">
                        <textarea class="form-control animated" id="new-review" name="comment" placeholder="Enter your review here and star rating below.." rows="3" required></textarea>
                        <div class="rate">
                            <input type="radio" id="star-5" name="rate" value="5" />
                            <label for="star-5" class="fas fa-star"></label>
                            <input type="radio" id="star-4" name="rate" value="4" />
                            <label for="star-4" class="fas fa-star"></label>
                            <input type="radio" id="star-3" name="rate" value="3" />
                            <label for="star-3" class="fas fa-star"></label>
                            <input type="radio" id="star-2" name="rate" value="2" />
                            <label for="star-2" class="fas fa-star"></label>
                            <input type="radio" id="star-1" name="rate" value="1" />
                            <label for="star-1" class="fas fa-star"></label>
                        </div>
                        <div class="text-right mt-1">
                            {% if request.user.is_authenticated or request.user.is_superuser %}
                                <button class="btn btn-review" type="submit">Save</button>
                            {% else %}
                                <p class="login-text"><a href="{% url 'account_login' %}">Login</a> to write a review</p>
                            {% endif %}
                        </div>
                    </form>
                </div>
            </div>
            <!-- Reviews written on product -->
            <div class="row">
                <div class="col-md-12">
                    {% if reviews %}
                        <h5 class="review-h5">Reviews</h5>
                        <hr>
                    {% endif %}
                    {% for review in reviews %}
                        <div class="review-heading">
                            <i class="fa fa-star {% if review.rate > 4 %} checked {% endif %}"></i>
                            <i class="fa fa-star {% if review.rate > 3 %} checked {% endif %}"></i>
                            <i class="fa fa-star {% if review.rate > 2 %} checked {% endif %}"></i>
                            <i class="fa fa-star {% if review.rate > 1 %} checked {% endif %}"></i>
                            <i class="fa fa-star {% if review.rate > 0 %} checked {% endif %}"></i>
                            <p class="blue-text admin-order-text"><i class="far fa-user"></i> {{ review.user.username }}</p>
                            <p class="admin-order-text">{{ review.created_at }}</p>
                        </div>
                        <div class="review-body mt-2">
                            <p>{{ review.comment }}</p>
                        </div>
                        <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <!-- If using the search field--> 
        {% if search_term %}
        <!-- Breadcrumb -->
        <div class="breadcrumb">
            <ol class="breadcrumb mt-5">
              <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i></a></li>
              <li class="breadcrumb-item active" aria-current="page">{{ search_term }}</li>
            </ol>
        </div>
        <!-- Search header --> 
        <h2 class="product-header">Search for {{ search_term }}</h2>
        <div class="row">
            <div class="col-sm-8">
                <!-- Search text --> 
                <p class="product-header-text">   
                    We could find {{ products|length }} products that matched your search <strong>"{{ search_term }}"</strong>
                </p>
            </div>
                <div class="col-sm-4">
                    <div class="dropdown product-filter-price">
                        <!-- Sort by button --> 
                        <button class="btn btn-outline-dark btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            SORT BY
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'products' %}?q={{ search_term }}&sort=price&direction=asc">Price: low to high</a>
                            <a class="dropdown-item" href="{% url 'products' %}?q={{ search_term }}&sort=price&direction=desc">Price: high to low</a>
                            <a class="dropdown-item" href="{% url 'products' %}?q={{ search_term }}&sort=sku&direction=asc">Oldest to newest</a>
                            <a class="dropdown-item" href="{% url 'products' %}?q={{ search_term }}&sort=sku&direction=desc">Newest to oldest</a>
                        </div>
                    </div>
                </div>
            <hr class="w-100 mb-1">
        </div>
        {% endif %}
        <!-- If using a category -->
        {% for category in current_categories %}
        <!-- Breadcrumb -->
        <div class="breadcrumb">
            <ol class="breadcrumb mt-5">
              <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i></a></li>
              <li class="breadcrumb-item active" aria-current="page">{{ category.friendly_name }}</li>
            </ol>
        </div>
            <!-- Category name --> 
            <h2 class="product-header">{{ category.friendly_name }}</h2>
            <div class="row">
                <div class="col-sm-8">
                    <!-- Text for each category --> 
                    <p class="product-header-text">   
                        {{ category.category_text }}
                    </p>
                </div>
                <div class="col-sm-4">
                    <div class="dropdown product-filter-price">
                        <!-- Sort by button --> 
                        <button class="btn btn-outline-dark btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          SORT BY
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'products' %}?sort=price&direction=asc&category={{ category.name }}">Price: low to high</a>
                            <a class="dropdown-item" href="{% url 'products' %}?sort=price&direction=desc&category={{ category.name }}">Price: high to low</a>
                            <a class="dropdown-item" href="{% url 'products' %}?sort=sku&direction=asc&category={{ category.name }}">Oldest to newest</a>
                            <a class="dropdown-item" href="{% url 'products' %}?sort=sku&direction=desc&category={{ category.name }}">Newest to oldest</a>
                        </div>
                    </div>
                </div>
            </div>
            <hr class="w-100 mb-1">
        {% endfor %}
        <div class="row">
            <!-- Product container --> 
            <div class="product-container">
                <div class="row">
                    {% for product in products %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card h-100 border-0">
                                <!-- Product image --> 
                                <a href="{{ product.get_absolute_url }}">
                                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                                </a>
                                <hr class="hr-desktop">
                                <div class="product-name">
                                     <!-- Product name --> 
                                    <p class="mb-0">{{ product.name }}</p>
                                    <!-- Product price --> 
                                    <p class="lead mb-0 text-left font-weight-bold">€ {{ product.price }}</p>
                                </div>
                                <hr class="hr-mobile">
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

products/templates/products/racket.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <h2 class="product-header">PADEL RACKET</h2>
            <div class="row">
                <div class="col-sm-8">
                    <p class="product-header-text">
                        Paddle rack from well-known brands such as Bullpadel, Adidas, Head, and Wilson. All our racks are carefully selected and tested, to ensure the quality of the rack.
                        We have paddle racks for all types of players from beginners to advanced players. Develop your own game with one of our paddle rackets and take yourself to new levels.
                    </p>
                </div>
                <div class="col-sm-4">
                    <div class="dropdown product-filter-price">
                        <button class="btn btn-outline-dark btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          SORT BY
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Populars</a>
                            <a class="dropdown-item" href="#">Price: low to high</a>
                            <a class="dropdown-item" href="#">Price: hight to low</a>
                            <a class="dropdown-item" href="#">Oldest to newest</a>
                            <a class="dropdown-item" href="#">Newest to oldest</a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <button type="button" class="btn btn-outline-dark">Adidas</button>
                    <button type="button" class="btn btn-outline-dark">Bullpadel</button>
                    <button type="button" class="btn btn-outline-dark">Head</button>
                    <button type="button" class="btn btn-outline-dark">Wilson</button>
                </div>
            <hr class="w-100 mb-1">
            </div>
        <div class="row">
            <div class="product-container">
                <div class="row">
                    {% for product in products %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card h-100 border-0">
                                {% if product.image %}
                                <a href="{% url 'product_detail' product.id %}">
                                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                                </a>
                                {% else %}
                                <a href="{% url 'product_detail' product.id %}">
                                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                                </a>
                                {% endif %}
                                <div class="product-name">
                                    <p class="mb-0">{{ product.name }}</p>
                                    <p class="mb-0">{{ product.price }} €</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}